### ISSUE TITLE
Components rendered at /pattern-preview using cached css?

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/ilo_base_theme#55]
I'm trying to write tests for a Twig component using the base theme. I've made changes to both the twig and the styles package. So I rebuild the project assets and then run `pnpm --filter twig start:theme` which runs `docker compose up -d` and then `pnpm --filter twig cy:open` which should open cypress. All good except when cypress opens, I'm still seeing the old version of the component without my changes to stylesheets.
 
My test calls the page like this:

```js
import fixture from "../../fixtures/factlistcard.json";

const url = `/pattern-preview?id=factlistcard&fields=${encodeURI(
  JSON.stringify(fixture)
)}`;

describe("Factlist card", () => {
  beforeEach(() => {
    cy.visit(url);
    cy.get(".ilo--card__type__factlist").as("card");
  });
...    
```

I'm wondering if for some reason `/pattern-preview` doesn't use the local version of the component unlike` /admin/appearance/ui/patterns/detailcard`?

**Comment by ademarco** [comment]
hello @justintemps you would need to run the theme container by mounting the current components and css directories in it, so that the new DS code is picked up. See what we do in the test workflow here https://github.com/international-labour-organization/designsystem/blob/develop/.github/workflows/test.yml#L63:

```yml
      - name: Run theme container
        run: |
          echo "${{ secrets.ILO_BASE_THEME_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
          docker run -d --name theme -p 8082:80 -v "${{ github.workspace }}"/packages/twig/dist/components:/opt/drupal/modules/ilo_base_theme_companion/dist/components -v "${{ github.workspace }}"/packages/twig/dist/styles/index.css:/opt/drupal/modules/ilo_base_theme_companion/dist/index.css ghcr.io/international-labour-organization/ilo_base_theme:1.x
```

Below the command in a more readable manner:

```shell
docker run -d \
  --name theme \
  -p 8082:80 \
  -v "./packages/twig/dist/components:/opt/drupal/modules/ilo_base_theme_companion/dist/components" \
  -v "./packages/twig/dist/styles/index.css:/opt/drupal/modules/ilo_base_theme_companion/dist/index.css" \
  ghcr.io/international-labour-organization/ilo_base_theme:1.x
```

You run the command above from the DS codebase, so that the paths `./packages/twig/dist...` are picked up correctly.
